# Generated by Django 5.1.1 on 2024-10-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_alter_movie_thumbnail_alter_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='watch_list',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='watch_history',
        ),
        migrations.DeleteModel(
            name='watch_list',
        ),
    ]
