# Generated by Django 5.1.1 on 2024-10-31 03:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0004_watch_history_watch_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_history',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='watch_history',
            name='user_id',
        ),
        migrations.AddField(
            model_name='watch_history',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moves.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch_history',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watch_history',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
