# Generated by Django 5.1.1 on 2024-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
